### ISSUE TITLE
Static everywhere

### ISSUE THREAD

**Issue by NotGGhost** [alphartdev/BungeeAdminTools#17]
Do you even java?

**Comment by Evoltr** [comment]
Yesyes am java dev

**Comment by Fireflies** [comment]
All the `static` and complete disregard for OOP ;-;

**Comment by alphartdev** [comment]
Do you even set out your arguments?
If you think that static is always a bad thing, then sorry for you but you're a bad coder.

Learn to do so and then I'll be glad to see how we could improve BAT design.

**Comment by Fireflies** [comment]
Sorry for not replying sooner @alphartdev, was out for a swim.

You have no grounds to call people bad programmers.
- Your package names do not adhere to the java naming conventions.
- You use a singleton where there need not be one which is considered bad practice. 
- Your `SQLQueries` class is both improperly named (`SqlQueries`) and full of unorganised code.
- Your idea of a modular system goes completely against modular design. 
- Your code is barely legible which is considered an awful practice. 
- There is no consistent style in your code.

Please, say something else, I'd love a good laugh. :balloon:

**Comment by alphartdev** [comment]
Alright, let's play this game :D
- my package are wrong my bad, though it has nothing to do with OOP standards
- concerning the singleton, as always you didn't quote anything concrete. If you're talking about the major one (BAT class), it allows a far better readability of the code and is used by tons of plugins. Otherwise in fact it doesn't fit in the correct definition of when a singleton should be used, I'll grant you that.
....
and that's it.
All your other arguments are just pure subjective views with like zero arguments. Do you want me to prove it? Alright let's go :
- "Your idea of a modular system goes completely against modular design." Any concrete arguments ? All modules are independent from each others except the core one which is always loaded.
- "Your code is barely legible which is considered an awful practice." and "There is no consistent style in your code." These sentences are basically the same and as for the criticism against the modular system, you have no concrete arguments. Yeah one or two tabs are sometime missing when accepting some PR and that's it. Otherwise the code is consistent : between 120 and 140 chars at each line, each big enough methods contains several steps which are separated by a carriage return...

Anyway, all I want to say is: as long as you don't give clear arguments of why something is wrong, it has absolutely **no value** to say it's wrong. As you've seen I totally admit that there might be minor code mistakes (and maybe even debatable designs), but BAT is clearly coded using the OO paradigm, and you can try to break this theory but you'll just fail as most of the code is built using polymorphism and other OOP concepts.

**Comment by ItsJamesJ** [comment]
@Fireflies - there is no need to be a dick. If you can improve @alphartdev's code, then do so. But don't sit behind your computer's monitor bitching about his code, if you're just going to critisize him, actually help him...

**Comment by Evoltr** [comment]
![saltyy](https://cloud.githubusercontent.com/assets/8143868/9156172/4e23b1d6-3ed1-11e5-940d-98f1d24c95ec.jpg)

**Comment by Web2201** [comment]
I didn't look at the code at all, but I'm just gonna agree with @Fireflies

**Comment by Fireflies** [comment]
I'll happily send a PR upstream if @alphartdev would like @ItsJamesJ, all he has to do is ask. I did offer him my plugin once complete which he could then decompile if he wished, indirectly helping him if he wished to re-use any of my code.

Your 'modules' are simple on-off toggles and the SQLQueries class is what breaks their modularity, if you moved the queries into the module packages then yes, you would be heading in the right direction for a somewhat modular design.

Singletons aren't designed for lazy access, you imply it's a good idea simply because other plugins use it but it's not despite a possible increase in legibility.

Regarding code legibility, this is something that is common sense and requires no concrete argument.

Consistent formatting/style and legibility are not the same thing, I don't know where this came from.

**Comment by Fireflies** [comment]
I will admit I was wrong about the OOP, I must have been looking at some other code when writing that.

**Comment by Fireflies** [comment]
And finally because GitHub mobile doesn't support editing; use a boolean for on-off states.. I have no idea why you're using constant `Integer`s to indicate status..

**Comment by ItsJamesJ** [comment]
I'm not going to take any side on this, I just think that if you're going to blatantly criticise someone's code, you should at least make an attempt to help them at the same time.

**Comment by Web2201** [comment]
With that I agree

**Comment by MeltedLux** [comment]
@ItsJamesJ rm -rf repo and restart

**Comment by alphartdev** [comment]
I hope you'll pardon me for my bad words,
@MeltedLux go FUCK yourself!
We're actually trying to figure out what's wrong, you probably figured out that there was a bit of tension and you're just making everything harder, so if you don't have anything useful to say, I repeat it: FUCK you. Am I clear? Thanks

@Fireflies Didn't think about the queries class problem, thanks for pointing it out. I'm gonna create a class for each module.
Concerning the singleton, what I mean by legibility, is that I find it easier to read to do `BAT.getInstance()` each time I need to access something important in the plugin rather than passing it to the function as a parameter.
Concerning global formatting, some PR messed it up a bit, but I'm still pretty convinced that it's pretty consistent, do you have anything particular in mind (tabs, brackets ?)
Finally for the integer as an indicator of state for modules, I was planning to add a third state for module who tried to load but failed (so there would have been: unloaded, loading failed, loaded). Never used it at the end so that might in fact be better to use Integer.
Finally for your offer of code, I still think that BAT isn't a total mess and I'm not wanting to copy/paste full block of code as it's (for now) working fine. Though if you have any other programming advices, I'll be glad to listen to them, I don't promise I'll apply them but I always love to have suggestions.

@ItsJamesJ Ty for your support, some people are fine in this conversation (I took a bad step with @Fireflies but he definitely doesn't look mean) but some others aren't and I'm glad you confirm this to me.

**Comment by Fireflies** [comment]
I would have recommended a `State` enum over three `Integer`s but that's just me. 

For coding styles I generally try to adhere as closely to [Google's java style][gjs] as it's an incredibly clear and straightforward style, plus it offers IntelliJ and Eclipse formatter profiles.

Not using my code is probably for the best for legacy purposes, the main plugin is essentially just a module manager and handles all database connections while seperate JAR files actually house the module code. (Loaded through the plugin though, not as extra bungee plugins)

[gjs]: http://google.github.io/styleguide/javaguide.html

**Comment by GGhosted** [comment]
I hope you'll pardon me for my bad words,
@MeltedLux go FUCK yourself!
We're actually trying to figure out what's wrong, you probably figured out that there was a bit of tension and you're just making everything harder, so if you don't have anything useful to say, I repeat it: FUCK you. Am I clear? Thanks


See, that's the problem, you (alphartdev) didn't fuck yourself hard enough.

**Comment by ItsJamesJ** [comment]
@GGhosted - now you're just being a dick. Just leave this issue, and
preferably leave this repository. You're just being a pain. You've got
nothing useful to contribute, so just leave.

On Sunday, August 9, 2015, GGhosted <notifications@github.com> wrote:

> I hope you'll pardon me for my bad words,
> @MeltedLux <https://github.com/MeltedLux> go FUCK yourself!
> We're actually trying to figure out what's wrong, you probably figured out
> that there was a bit of tension and you're just making everything harder,
> so if you don't have anything useful to say, I repeat it: FUCK you. Am I
> clear? Thanks
>
> See, that's the problem, you (alphartdev) didn't fuck yourself hard
> enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alphartdev/BungeeAdminTools/issues/17#issuecomment-129242059>
> .
>


-- 

Lead Developer & Administrator of DatPixel Entertainment.

**Comment by GGhosted** [comment]
> @GGhosted - now you're just being a dick. Just leave this issue, and
> preferably leave this repository. You're just being a pain. You've got
> nothing useful to contribute, so just leave.

I haven't got anything useful to contribute - true
Just leave - no
You're just being a pain - true
Preferably leave this repository - no
Now you're just being a dick - true even though it was just meant to be a joke

**Comment by GGhosted** [comment]
> @GGhosted - now you're just being a dick. Just leave this issue, and
> preferably leave this repository. You're just being a pain. You've got
> nothing useful to contribute, so just leave.

I haven't got anything useful to contribute - true
Just leave - How about no?
You're just being a pain - true
Preferably leave this repository - fuck no
Now you're just being a dick - true even though it was just meant to be a joke. I'm not even the saltiest one here. :/

**Comment by GGhosted** [comment]
If you'd like to send a complaint to my complaint department, you may do so at noreply@ghosted.me or visit http://www.saxroll.com/

**Comment by alphartdev** [comment]
@NotGGhost Please grow up, you're just being childish. If it was really supposed to be a joke, then tell so and tell that you didn't want to go this far and that's it. End of the story.

@Fireflies Thanks for the google conventions, definitely going to use the formatter!

**Comment by NotGGhost** [comment]
> @NotGGhost Please grow up, you're just being childish. I

Childish like your code?


> If it was really supposed to be a joke, then tell so and tell that you didn't want to go this far and that's it. End of the story.

Nah, telling you to go fuck yourself harder was the joke, since you told others to do that.

**Comment by Evoltr** [comment]
LETS ALL JUST BE FWENDS!!!

**Comment by NotGGhost** [comment]
Dank memes

**Comment by MeltedLux** [comment]
Issue was not resolved and closed, love it. :^ )

**Comment by alphartdev** [comment]
I'm not even mad, that's amazing to see how your life is empty :D

**Comment by MeltedLux** [comment]
bb personal insults will get you nowhere on the internet :^ )

**Comment by alphartdev** [comment]
So funny coming from the guy who has no other idea than deleting the repo. bye bye

**Comment by NotGGhost** [comment]
WHAT THE FUCK DID YOU JUST SAY ABOUT ME? I HAVE A POTATO THAT GIVES OF A HIGHLY RADIOACTIVE SINGLE WHICH HAS THE POWER TO LUNCH ITSELF AT 50,000 MILES PER HOUR.  I HIGHLY SUGGEST YOU DON'T WANT TO SHIT TALK ME AND MY POTATO OR ELSE YOU'RE GOING TO BE CRUSHED INTO A PAN CAKE THAT THEY'LL EAT AT THREE MILE ISLAND 2.0.

**Comment by ItsJamesJ** [comment]
>WHAT THE FUCK DID YOU JUST SAY ABOUT ME? I HAVE A POTATO THAT GIVES OF A HIGHLY >RADIOACTIVE SINGLE WHICH HAS THE POWER TO LUNCH ITSELF AT 50,000 MILES PER >HOUR. I HIGHLY SUGGEST YOU DON'T WANT TO SHIT TALK ME AND MY POTATO OR ELSE >YOU'RE GOING TO BE CRUSHED INTO A PAN CAKE THAT THEY'LL EAT AT THREE MILE ISLAND >2.0.
*signal
*pancake
*launch.

Why don't you all just stfu?

**Comment by NotGGhost** [comment]
> Why don't you all just stfu?

That's it? Close enough taking in mind I did that shit on my phone. :/

**Comment by ItsJamesJ** [comment]
You're all just being dicks to each other. I seriously lost respect for some users I thought were actually decent human beings, just from this issue, there was no need to be a dick to @alphartdev .-.

**Comment by NotGGhost** [comment]
You do know this was all just a huge joke since there was a lil' static ab00se, right? If you took anything said here seriously, then I sincerely feel sorry for you.

**Comment by ItsJamesJ** [comment]
I'm not taking this seriously, but you took it was past a joke.
It was a joke at first, but then it just ended in you all being dicks.

**Comment by MeltedLux** [comment]
@ItsJamesJ https://cd0.us/sAltY.png

**Comment by alphartdev** [comment]
Alright, enough with that. Go find an occupation to fill your life please.
