### ISSUE TITLE
Error when doing a lookup on a imported ban

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [alphartdev/BungeeAdminTools#8]
Error when doing a lookup, I did _/bat lookup brockie98 ban_
http://pastebin.com/yWDy5FbZ

**Comment by alphartdev** [comment]
Hi,
the issue might be what we talked about in Conversations. Did this player join before the lookup (but after the import) ?

**Comment by TheOnlyRealTGS** [comment]
I took the server down when I imported everything, so that's not possible

**Comment by alphartdev** [comment]
No, that's not what I meant, here is an schema : 
Import process --> Did you player join between those two processes ? --> Lookup on player

**Comment by TheOnlyRealTGS** [comment]
I can't say for sure, but I think so

**Comment by alphartdev** [comment]
The import method will include the addition of a row to the BAT_players table in order to avoid most of the lookup errors, I'll do it at the same time as the lookup refactorization...
So I'll close that till it's done (will probably be done in the week from 16th to 23th February as I've got my exam now). Also I think the error you sent is not complete, if you get it again could you pastebin the whole error please ?

**Comment by TheOnlyRealTGS** [comment]
Sounds good, and that was all there was. It is complete, just upside down.
